apiVersion: v1
kind: Service
metadata:
  name: scribble-backend-staging-service
spec:
  type: NodePort
  selector:
    app: scribble-backend-staging
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
