
apiVersion: v1
kind: Service
metadata:
  name: scribble-backend-stable
spec:
  selector:
    app: scribble-backend-dev-rollout
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: scribble-backend-preview
spec:
  selector:
    app: scribble-backend-dev-rollout
  ports:
  - port: 80
    targetPort: 8080
