apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: scribble-backend
spec:
  replicas: 10
  selector:
    matchLabels:
      app: scribble-backend-dev-rollout
  template:
    metadata:
      labels:
        app: scribble-backend-dev-rollout
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: scribble-backend
        image: bsalsingh/scribble-api:1753983755
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: scribble-secret
  strategy:
    canary:
      canaryService: scribble-backend-preview
      stableService: scribble-backend-stable
      trafficRouting:
        nginx:
          stableIngress: scribble-backend-stable-ingress
      steps:
      - setWeight: 20
      - pause: {duration: 300}     # wait 5 minutes for traffic
      - analysis:
          templates:
          - templateName: canary-request-check
          args:
          - name: prometheus-address
            value: http://prometheus.monitoring.svc.cluster.local:9090
          - name: ingress-host
            value: myapp.local
      - setWeight: 100
