
---
apiVersion: v1
kind: Service
metadata:
  name: scribble-backend-preview
spec:
  type: NodePort
  selector:
    app: scribble-backend-dev-rollout
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30085  # optional, must be different
    protocol: TCP


# services.yaml
apiVersion: v1
kind: Service
metadata:
  name: scribble-backend-stable
  namespace: dev
spec:
  selector:
    app: scribble-backend-dev-rollout
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: scribble-backend-preview
  namespace: dev
spec:
  selector:
    app: scribble-backend-dev-rollout
  ports:
  - port: 80
    targetPort: 8080
